### ISSUE TITLE
Multiple windows error with only one window.

### ISSUE THREAD

**Issue by kcopenhagen** [mathworks/matlab-proxy#32]
### Summary

Whenever I working an interactive window for a while and then close it and disconnect for a while and go back to it, it pops up a warning saying I have matlab open in multiple windows asking if I want to continue on the other window or the current one. It works find once I click continue in this window it's just mildly annoying to have to click that every time.

**Comment by prabhakk-mw** [comment]
Hi @kcopenhagen 

This should now be fixed with [v0.17.0](https://pypi.org/project/matlab-proxy/) of `matlab-proxy`.
Kindly verify by upgrading your packages using:

`python -m pip install --upgrade matlab-proxy`

Please do let us know if upgrading to this version did not resolve the reported issue.

Thank you!
